export const DO_REGISTRATION='DO_REGISTRATION'
export const ERROR='ERROR'
export const AUTH_START='AUTH_START'
export const AUTH_SUCCESS='AUTH_SUCCESS'
export const AUTH_FAIL='AUTH_FAIL'
export const CLEAR_TOKEN_ID="CLEAR_TOKEN_ID"